import assert from 'node:assert/strict';
import fs from 'node:fs';
import {offensiveContribution} from '../lib/game-score.ts';
import {playerMatchStats,leaguePlayerStats} from '../lib/player-match.ts';
import {extractShots} from '../lib/shl.ts';
assert.equal(offensiveContribution({goals:1,firstAssists:1,secondAssists:1,xg:2}),3);
assert.equal(offensiveContribution({goals:1,firstAssists:null,secondAssists:0,xg:1}),null);
assert.equal(offensiveContribution({goals:1,firstAssists:0,secondAssists:0,xg:NaN}),null);
assert.equal(offensiveContribution({goals:1.5,firstAssists:0,secondAssists:0,xg:1}),null);
const shot={id:'s',eligible:true,emptyNet:false,period:1,home:true,player:'Scorer',xg:.2,outcome:'goal',assists:{first:'Passer',second:null}};
const g={id:'a',date:'2026-10-01',home:'H',away:'A',playerDataVersion:1,shots:[shot]};
let r=playerMatchStats(g);assert.equal(r.find(p=>p.name==='Passer').offense,.7);assert.equal(r.find(p=>p.name==='Passer').attempts,0);assert.equal(r.find(p=>p.name==='Scorer').offense,.85);
assert.equal(playerMatchStats({...g,playerDataVersion:undefined})[0].offense,null);
assert.equal(playerMatchStats({...g,shots:[{...shot,assists:undefined}]})[0].offense,null);
assert.equal(playerMatchStats({...g,shots:[shot,{...shot,id:'ot',period:4}]})[0].goals,1);
assert.equal(playerMatchStats({...g,shots:[{...shot,emptyNet:true}]}).length,0);
const g2={...g,id:'b',date:'2026-10-02'};
assert.equal(leaguePlayerStats([g,g2]).find(p=>p.name==='Passer').offense,1.4);
assert.equal(leaguePlayerStats([g,{...g2,playerDataVersion:undefined}]).find(p=>p.name==='Passer').offense,null);
assert.equal(leaguePlayerStats([g,{...g2,home:'A',away:'H'}],'all','home').find(p=>p.team==='H'&&p.name==='Passer').offense,.7);
const keeper=side=>({eventId:side==='home'?1:2,type:'goalkeeper',period:1,time:'00:00',isEntering:true,eventTeam:{place:side},player:{firstName:'Keeper',familyName:side}});
const goal={eventId:3,revision:1,type:'goal',period:1,time:'01:00',eventTeam:{place:'home'},locationX:50,locationY:10,player:{firstName:'A',familyName:'Scorer'},assists:{first:{firstName:'B',familyName:'Passer'}}};
const parsed=extractShots([keeper('home'),keeper('away'),goal,{...goal,revision:2,assists:{second:{firstName:'C',familyName:'Passer'}}}]);
assert.deepEqual(parsed[0].assists,{first:null,second:'C Passer'});
console.log('PASS Game Score offensive contribution: weights, missing data, assist-only players, corrected assists, scope and aggregation.');
