import assert from 'node:assert/strict';
import fs from 'node:fs';
import {offensiveContribution} from '../lib/game-score.ts';
import {playerMatchStats,leaguePlayerStats} from '../lib/player-match.ts';
import {extractShots} from '../lib/shl.ts';
assert.equal(offensiveContribution({goals:1,firstAssists:1,secondAssists:1,xg:2}),3);
assert.equal(offensiveContribution({goals:1,firstAssists:null,secondAssists:0,xg:1}),null);
assert.equal(offensiveContribution({goals:1,firstAssists:0,secondAssists:0,xg:NaN}),null);
assert.equal(offensiveContribution({goals:1.5,firstAssists:0,secondAssists:0,xg:1}),null);
const shot={id:'s',eligible:true,emptyNet:false,period:1,home:true,player:'Scorer',xg:.2,outcome:'goal',assists:{first:'Passer',second:null}};
const g={id:'a',date:'2026-10-01',home:'H',away:'A',playerDataVersion:1,shots:[shot]};
let r=playerMatchStats(g);assert.equal(r.find(p=>p.name==='Passer').offense,.7);assert.equal(r.find(p=>p.name==='Passer').attempts,0);assert.equal(r.find(p=>p.name==='Scorer').offense,.85);
assert.equal(playerMatchStats({...g,playerDataVersion:undefined})[0].offense,null);
assert.equal(playerMatchStats({...g,shots:[{...shot,assists:undefined}]})[0].offense,null);
assert.equal(playerMatchStats({...g,shots:[shot,{...shot,id:'ot',period:4}]})[0].goals,1);
assert.equal(playerMatchStats({...g,shots:[{...shot,emptyNet:true}]}).length,0);
const g2={...g,id:'b',date:'2026-10-02'};
assert.equal(leaguePlayerStats([g,g2]).find(p=>p.name==='Passer').offense,1.4);
assert.equal(leaguePlayerStats([g,{...g2,playerDataVersion:undefined}]).find(p=>p.name==='Passer').offense,null);
assert.equal(leaguePlayerStats([g,{...g2,home:'A',away:'H'}],'all','home').find(p=>p.team==='H'&&p.name==='Passer').offense,.7);
const keeper=side=>({eventId:side==='home'?1:2,type:'goalkeeper',period:1,time:'00:00',isEntering:true,eventTeam:{place:side},player:{firstName:'Keeper',familyName:side}});
const goal={eventId:3,revision:1,type:'goal',period:1,time:'01:00',eventTeam:{place:'home'},locationX:50,locationY:10,player:{firstName:'A',familyName:'Scorer'},assists:{first:{firstName:'B',familyName:'Passer'}}};
const parsed=extractShots([keeper('home'),keeper('away'),goal,{...goal,revision:2,assists:{second:{firstName:'C',familyName:'Passer'}}}]);
assert.deepEqual(parsed[0].assists,{first:null,second:'C Passer'});
console.log('PASS Game Score offensive contribution: weights, missing data, assist-only players, corrected assists, scope and aggregation.');

// Defensive beta: attribution must survive revisions and never charge goalies/bench servers.
const {defensiveContribution}=await import('../lib/game-score.ts');
const {extractDefense}=await import('../lib/shl.ts');
assert.equal(defensiveContribution({penaltyMinutes:2,goalsAgainstOnIce:1}),-.8);
assert.equal(defensiveContribution({penaltyMinutes:0,goalsAgainstOnIce:0}),0);
assert.equal(defensiveContribution({penaltyMinutes:null,goalsAgainstOnIce:0}),null);
assert.equal(defensiveContribution({penaltyMinutes:0,goalsAgainstOnIce:1.5}),null);
const v={minorTime:'2',doubleMinorTime:'0',benchTime:'0',majorTime:'0',misconductTime:'0',gMTime:'0',mPTime:'0'};
const pen={eventId:4,type:'penalty',period:1,time:'02:00',revision:1,eventTeam:{place:'home'},player:{firstName:'A',familyName:'Defender'},variant:v};
const defEvents=[keeper('home'),keeper('away'),pen,{...pen,revision:2,variant:{...v,minorTime:'0',doubleMinorTime:'4'}}];
const parsedDefense=extractDefense(defEvents,[]);assert.deepEqual(parsedDefense.penalties,[{name:'A Defender',home:true,minutes:4}]);
assert.equal(extractDefense([keeper('home'),keeper('away'),{...pen,variant:{...v,benchTime:'2'}}],[]).penalties.length,0);
assert.equal(extractDefense([keeper('home'),keeper('away'),{...pen,period:4}],[]).penalties.length,0);
assert.equal(extractDefense([keeper('home'),keeper('away'),{...keeper('home'),eventId:8,time:'01:00',isEntering:false},pen],[]).penalties.length,0);
assert.equal(extractDefense([pen],[]).complete.home,false);
assert.equal(extractDefense([keeper('home'),keeper('away'),{...pen,variant:undefined}],[]).complete.home,false);
const ds={...shot,home:false,defendingSkaters:['Defender','Keeper home'],goalie:{id:'Keeper home',name:'Keeper home'},assists:{first:null,second:null}};
const dg={...g,shots:[ds],defenseData:{version:1,complete:{home:true,away:true},penalties:[{name:'Defender',home:true,minutes:2}]}};
const dr=playerMatchStats(dg);assert.equal(dr.find(r=>r.name==='Defender').defense,-.8);assert.equal(dr.find(r=>r.name==='Defender').attempts,0);assert.equal(dr.some(r=>r.name==='Keeper home'),false);
assert.equal(playerMatchStats({...dg,defenseData:undefined}).find(r=>r.name==='Defender').defense,null);
assert.equal(extractDefense([], [{...ds,defendingSkaters:undefined}]).complete.home,false);
assert.equal(leaguePlayerStats([dg,{...dg,id:'second'}]).find(r=>r.name==='Defender').defense,-1.6);
assert.equal(leaguePlayerStats([dg,{...dg,id:'second',defenseData:undefined}]).find(r=>r.name==='Defender').defense,null);
assert.equal(leaguePlayerStats([dg,{...dg,id:'second',home:'A',away:'H'}],'all','home').find(r=>r.team==='H'&&r.name==='Defender').defense,-.8);
const actual=JSON.parse(fs.readFileSync(new URL('../data/shl-2026.json',import.meta.url),'utf8')).games.find(g=>g.id==='shl-zmrkc06ec8');
if(actual?.defenseData){const r=playerMatchStats(actual).find(r=>r.name==='Gustav Lindström');assert.equal(r.penaltyMinutes,2);assert.equal(r.goalsAgainstOnIce,1);assert.equal(r.defense,-.8);}
console.log('PASS defensive beta: missing coverage, on-ice attribution, bench penalties, revisions, goalies, scope and aggregation.');
