import fs from 'node:fs';import assert from 'node:assert/strict';import {extractShots,probability} from '../lib/shl.ts';import {perspective} from '../lib/hockey.ts';
const snapshot=JSON.parse(fs.readFileSync(new URL('../data/shl-2026.json',import.meta.url)));const model=JSON.parse(fs.readFileSync(new URL('../data/xg-model.json',import.meta.url)));
for(const game of snapshot.games){const stat=game.stats.all;assert.equal(stat.cf+stat.ca,game.shots.length);assert.equal(stat.gf+stat.ga,game.shots.filter(s=>s.outcome==='goal').length);assert(game.shots.every(s=>s.eligible&&!s.emptyNet&&s.period<=3&&s.xg>=0&&s.xg<1));assert.equal(perspective(game,game.away,'all').xgf,stat.xga);assert(!game.stats.five);assert(Math.abs(game.shots.filter(s=>s.home).reduce((a,s)=>a+s.xg,0)-stat.xgf)<1e-10);}
const events=[{eventId:1,type:'goalkeeper',period:1,time:'00:00',eventTeam:{place:'home'},isEntering:true},{eventId:2,type:'goalkeeper',period:1,time:'00:00',eventTeam:{place:'away'},isEntering:true},{eventId:3,eventUuid:'shot',revision:1,type:'shot',period:1,time:'01:00',eventTeam:{place:'home'},locationX:100,locationY:0,goalSection:2},{eventId:3,eventUuid:'shot',revision:2,type:'shot',period:1,time:'01:00',eventTeam:{place:'home'},locationX:120,locationY:0,goalSection:2},{eventId:4,type:'goalkeeper',period:1,time:'01:01',eventTeam:{place:'away'},isEntering:false},{eventId:5,type:'shot',period:1,time:'01:02',eventTeam:{place:'home'},locationX:50,locationY:0,goalSection:2},{eventId:6,type:'shot',period:4,time:'01:00',eventTeam:{place:'home'},locationX:50,locationY:0,goalSection:2}];
const shots=extractShots(events);assert.equal(shots.length,2);assert.equal(shots[0].x,120);assert(shots[0].eligible);assert(!shots[1].eligible&&shots[1].emptyNet);assert.equal(probability({...shots[0],outcome:'blocked'},model),0);assert(model.validation.brier<model.validation.baselineBrier);assert(model.validation.logLoss<model.validation.baselineLogLoss);console.log('PASS: snapshot consistency, away perspective, revisions, empty net and OT exclusion, model baseline comparison.');

const {goalieStats}=await import('../lib/goalies.ts');
const keep=(place,name,time,id)=>({eventId:id,type:'goalkeeper',period:1,time,eventTeam:{place},isEntering:true,player:{firstName:name,familyName:'Test'}});
const attempt=(outcome,time,id,home=true)=>({eventId:id,type:outcome==='goal'?'goal':'shot',period:1,time,eventTeam:{place:home?'home':'away'},locationX:100,locationY:0,goalSection:outcome==='saved'?1:outcome==='blocked'?-3:undefined});
const attributed=extractShots([keep('home','Home','00:00',1),keep('away','First','00:00',2),attempt('saved','00:01',3),attempt('missed','00:02',4),keep('away','Second','00:03',5),attempt('goal','00:04',6),attempt('blocked','00:05',7),attempt('saved','00:06',8,false)]).map(s=>({...s,xg:.2}));
assert.equal(attributed[0].goalie.name,'First Test');assert.equal(attributed[2].goalie.name,'Second Test');assert.equal(attributed[4].goalie.name,'Home Test');
const goalieGame={id:'keepers',date:'2026-09-01',home:'H',away:'A',shots:attributed};const stats=goalieStats([goalieGame]).rows;const first=stats.find(r=>r.name==='First Test'),second=stats.find(r=>r.name==='Second Test');assert.equal(first.shots,1);assert.equal(first.savePercentage,100);assert.equal(first.xga,.4);assert.equal(first.gsax,.4);assert.equal(second.gsax,-.8);assert.equal(second.savePercentage,0);assert.equal(stats.find(r=>r.name==='Home Test').team,'H');assert.equal(goalieStats([{...goalieGame,shots:attributed.map(s=>({...s,goalie:undefined}))}]).rows.length,0);console.log('PASS: goalie switches, defending team, saves percentage, missed and blocked shots, GSAx and unknown identities.');
