import {useEffect,useState} from 'react';
import {Info,ArrowLeft,ChevronRight,ExternalLink,RefreshCw,Share2} from 'lucide-react';
import {Table,TableHeader,TableBody,TableHead,TableRow,TableCell} from './ui/table';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from './ui/select';
import {Dialog,DialogTrigger,DialogContent,DialogHeader,DialogTitle,DialogDescription} from './ui/dialog';
import {ClubLogo} from './club-logo';
import {SpecialTeams} from './special-teams';
import {HA_TEAMS,haStandings,type HaSnapshot,type HaGame} from '../lib/ha';
const fmt=(v:number|null|undefined,d=1)=>v==null?'—':v.toLocaleString('sv-SE',{minimumFractionDigits:d,maximumFractionDigits:d});
function Club({team}:{team:string}){return <span className="league-team"><ClubLogo team={team} size={24} decorative/>{team}</span>}
function Rows({heads,rows}:{heads:string[];rows:React.ReactNode[][]}){return <Table className="xg-table"><TableHeader><TableRow>{heads.map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.map((row,i)=><TableRow key={i}>{row.map((c,j)=><TableCell key={j}>{c}</TableCell>)}</TableRow>)}</TableBody></Table>}
function Missing(){return <div className="inline-info ha-coverage"><Info size={18}/><p><strong>xG-underlag saknas.</strong> Hockeyallsvenskans publika matchhändelser saknar skottpositioner. xG, GSAx, skottkartor, xG-tabell och offensivt bidrag kan därför inte beräknas. Saknade värden visas som —.</p></div>}
function TeamSelect({label,value,onChange,all=false}:{label:string;value:string;onChange:(v:string)=>void;all?:boolean}){return <div className="picker"><label>{label}</label><Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{all&&<SelectItem value="all">Alla klubbar</SelectItem>}{HA_TEAMS.map(t=><SelectItem key={t} value={t}><ClubLogo team={t} size={22} decorative/>{t}</SelectItem>)}</SelectContent></Select></div>}
function Metrics({items}:{items:{label:string;value:string;note:string}[]}){return <div className="metric-grid ha-metric-grid">{items.map(i=><article className="metric" key={i.label}><div className="metric-label">{i.label}</div><div className="metric-value">{i.value}</div><p>{i.note}</p></article>)}</div>}
function GoalieLog({games,name,team,open}:{games:HaGame[];name:string;team:string;open:(g:HaGame)=>void}){const rows=games.flatMap(g=>(g.goalies||[]).filter(r=>r.name===name&&r.team===team).map(r=>({g,r}))).sort((a,b)=>b.g.date.localeCompare(a.g.date));return <>{rows.length?<Rows heads={['Datum','Motstånd','Räddningar','Skott på mål','Räddningsprocent','Insläppta','GSAx']} rows={rows.map(({g,r})=>[<button className="text-button" onClick={()=>open(g)}>{g.date}<ChevronRight size={14}/></button>,<Club team={g.home===team?g.away:g.home}/>,r.saves,r.saves+r.goals,`${fmt(r.savePercentage,2)} %`,r.goals,'—'])}/>:<p>Verifierad matchstatistik saknas för målvakten.</p>}<p className="chart-note">Ordinarie tid med båda målvakterna på isen. Säsongslistans officiella räddningsprocent inkluderar även förlängning och kan skilja sig.</p></>}
export function HaDashboard({snapshot,view,team,selectedId,onNavigate,onShare,onRefresh,syncing,message,range,onRangeChange:setRange,venue,onVenueChange:setVenue}:{snapshot:HaSnapshot;view:string;team:string;selectedId:string|null;onNavigate:(view:string,team?:string,id?:string|null)=>void;onShare:()=>void;onRefresh:()=>void;syncing:boolean;message:string;range:string;onRangeChange:(v:string)=>void;venue:string;onVenueChange:(v:string)=>void}){
 const [club,setClub]=useState('all'),[query,setQuery]=useState(''),[second,setSecond]=useState(HA_TEAMS.find(t=>t!==team)!),[sort,setSort]=useState('default'),[tab,setTab]=useState('table');
 useEffect(()=>{setClub('all');setQuery('');setSort('default');},[view]);
 const games=snapshot.games,standings=haStandings(games),own=standings.find(r=>r.team===team)!,official=snapshot.teams.find(r=>r.team===team)!;
 const selection=(t:string)=>{const s=games.filter(g=>(g.home===t||g.away===t)&&(venue==='all'||(venue==='home'?g.home===t:g.away===t))).sort((a,b)=>b.date.localeCompare(a.date)||b.id.localeCompare(a.id));return range==='all'?s:s.slice(0,Number(range));};
 const open=(g:HaGame)=>onNavigate('matches',g.home===team||g.away===team?team:g.home,g.id),selected=games.find(g=>g.id===selectedId);
 const heading=view==='team'?'Hur spelar laget?':view==='league'?'Hockeyallsvenskan under ytan.':view==='players'?'Vilka spelare producerar mest?':view==='goalies'?'Vilka målvakter räddar mest?':view==='special'?'Vad bidrar special teams med?':view==='compare'?'Jämför lagens prestation.':view==='data'?'Förstå siffrorna.':'Vad hände i matcherna?';
 const summary=(t:string)=>{const s=selection(t);let gf=0,ga=0,shots=0,complete=true;for(const g of s){const h=g.home===t;gf+=h?g.resultHome:g.resultAway;ga+=h?g.resultAway:g.resultHome;const n=h?g.homeShots:g.awayShots;if(n===null)complete=false;else shots+=n;}if(range==='all'&&venue==='all'){const official=snapshot.teams.find(r=>r.team===t);if(official&&official.games===s.length&&official.goals===gf){shots=official.shots;complete=true;}}return {games:s.length,gf,ga,shots:complete?shots:null,shooting:complete&&shots?gf/shots*100:null};};
 const matchList=(matches:HaGame[])=>matches.length?<Rows heads={['Datum','Hemma','Borta','Resultat','Avgjort','Skott på mål','xG']} rows={matches.map(g=>[<button className="text-button" onClick={()=>open(g)}>{g.date}<ChevronRight size={14}/></button>,<Club team={g.home}/>,<Club team={g.away}/>,`${g.resultHome}–${g.resultAway}`,g.decided==='FT'?'Ordinarie tid':g.decided==='OT'?'Förlängning':'Straffar',`${fmt(g.homeShots,0)}–${fmt(g.awayShots,0)}`,'—'])}/>:<p>Inga matcher i urvalet.</p>;
 if(selectedId)return selected?<><button className="button subtle" onClick={()=>onNavigate('matches')}><ArrowLeft size={16}/>Till matcherna</button><div className="page-heading"><div><span className="eyebrow">MATCHANALYS · {selected.date}</span><h1>{selected.home} – {selected.away}</h1></div></div><section className="panel ha-match-summary"><Club team={selected.home}/><strong>{selected.resultHome}–{selected.resultAway}</strong><Club team={selected.away}/><p>Skott på mål: {fmt(selected.homeShots,0)}–{fmt(selected.awayShots,0)} · Slutresultat inklusive eventuell förlängning och straffar</p></section><Missing/><section className="panel"><div className="panel-heading"><div><h2>Målvakter i matchen</h2><p>{selected.eventCoverage||'Verifierad matchstatistik saknas.'}</p></div></div>{selected.goalies?.length?<Rows heads={['Målvakt','Lag','Räddningar','Skott på mål','Räddningsprocent','Insläppta','GSAx']} rows={selected.goalies.map(r=>[<ClubName team={r.team} name={r.name}/>,r.team,r.saves,r.saves+r.goals,`${fmt(r.savePercentage,2)} %`,r.goals,'—'])}/>:<p>Verifierad målvaktsstatistik saknas för matchen.</p>}</section><section className="panel"><div className="panel-heading"><div><h2>Spelare i matchen</h2><p>Ordinarie tid med båda målvakterna på isen · Spelare med registrerade avslut eller assist</p></div></div>{selected.players?.length?<Rows heads={['Spelare','Lag','Mål','Första assist','Andra assist','Skott på mål','Skottförsök','xG']} rows={[...selected.players].sort((a,b)=>(b.goals+b.firstAssists+b.secondAssists)-(a.goals+a.firstAssists+a.secondAssists)||b.shots-a.shots).map(r=>[<ClubName team={r.team} name={r.name}/>,r.team,r.goals,r.firstAssists,r.secondAssists,r.shots,r.attempts,'—'])}/>:<p>Verifierad spelarstatistik saknas för matchen.</p>}</section><a className="text-link" href={selected.url} target="_blank" rel="noreferrer">Officiell matchkälla <ExternalLink size={14}/></a></>:<section className="panel"><h2>Matchen finns inte i underlaget</h2><button className="button subtle" onClick={()=>onNavigate('matches')}>Visa matcher</button></section>;
 return <><div className="page-heading"><div><span className="eyebrow">HOCKEYALLSVENSKAN · {snapshot.season}</span><h1>{heading}</h1></div><button className="button subtle share-button" onClick={onShare}><Share2 size={15}/>Dela vy</button></div>
 {view!=='data'&&<Missing/>}
 {['team','matches','compare'].includes(view)&&<><div className="filter-bar"><div className="table-mode" aria-label="Matchurval">{[['all','Hela säsongen'],['5','Senaste 5'],['10','Senaste 10']].map(([v,l])=><button key={v} className={range===v?'active':''} onClick={()=>setRange(v)}>{l}</button>)}</div><div className="picker"><label>Spelplats</label><Select value={venue} onValueChange={setVenue}><SelectTrigger aria-label="Spelplats"><SelectValue/></SelectTrigger><SelectContent>{[['all','Hemma & borta'],['home','Hemma'],['away','Borta']].map(([v,l])=><SelectItem key={v} value={v}>{l}</SelectItem>)}</SelectContent></Select></div></div><p className="selection-context">Officiella slutresultat och skott på mål, inklusive förlängning och straffavgörande.</p></>}
 {view==='team'&&<><section className="team-heading"><ClubLogo team={team} size={62} decorative/><div><h2>{team}</h2><p>{own.games} matcher · {own.wins} segrar · {own.points} poäng <small>Hela säsongen</small></p></div></section><Metrics items={[{label:'Målskillnad',value:`${summary(team).gf}–${summary(team).ga}`,note:`${summary(team).games} matcher i urvalet`},{label:'Skotteffektivitet',value:`${fmt(summary(team).shooting,2)}${summary(team).shooting===null?'':' %'}`,note:'Gjorda mål / skott på mål i matchurvalet'},{label:'Corsi-andel',value:`${fmt(official.corsi,2)} %`,note:'Officiellt Corsi-mått · hela säsongen'},{label:'xG',value:'—',note:'Skottpositioner saknas i källan'}]}/><section className="panel"><div className="panel-heading"><div><h2>Match för match</h2><p>Tryck på datumet för spelar- och målvaktsstatistik.</p></div></div>{matchList(selection(team))}</section></>}
 {view==='league'&&<><section className="panel"><div className="panel-heading"><div><h2>{tab==='table'?'Faktisk tabell':'Lagens statistik'}</h2><p>Hela säsongen · {games.length} spelade matcher</p></div><div className="table-mode"><button className={tab==='table'?'active':''} onClick={()=>setTab('table')}>Tabell</button><button className={tab==='stats'?'active':''} onClick={()=>setTab('stats')}>Prestation</button><button disabled title="Skottpositioner saknas">xG-tabell</button></div></div>{tab==='table'?<Rows heads={['#','Lag','Matcher','Segrar','Mål','Målskillnad','Poäng']} rows={standings.map((r,i)=>[i+1,<button onClick={()=>onNavigate('team',r.team)}><Club team={r.team}/></button>,r.games,r.wins,`${r.gf}–${r.ga}`,r.gf-r.ga,<strong>{r.points}</strong>])}/>:<Rows heads={['Lag','Matcher','Mål','Skott på mål','Skotteffektivitet','Corsi %','Fenwick %','xG']} rows={[...snapshot.teams].sort((a,b)=>(b.corsi??-1)-(a.corsi??-1)).map(r=>[<button onClick={()=>onNavigate('team',r.team)}><Club team={r.team}/></button>,r.games,r.goals,r.shots,r.shots?`${fmt(r.goals/r.shots*100,2)} %`:'—',fmt(r.corsi,2),fmt(r.fenwick,2),'—'])}/>}</section><p className="chart-note">Slutresultat ger 3 poäng för ordinarie vinst, 2 för förlängnings- eller straffvinst och 1 för motsvarande förlust. Tabellen sorteras efter poäng, målskillnad och gjorda mål; helt lika lag sorteras alfabetiskt. Corsi och Fenwick visas enligt ligans officiella statistikurval och beskriver avslutsvolym, inte chanskvalitet.</p></>}
 {view==='special'&&<SpecialTeams team={team} league="ha" data={snapshot.special}/>}
 {(view==='players'||view==='goalies')&&<><section className="panel players-panel"><div className="panel-heading"><div><h2>{view==='players'?'Spelare':'Målvakter'} · {club==='all'?'hela ligan':club}</h2><p>Officiell säsongsstatistik · inklusive förlängning</p></div><div className="picker"><label>Sortera</label><Select value={sort} onValueChange={setSort}><SelectTrigger aria-label="Sortera statistik"><SelectValue>{sort==='shots'?'Skott på mål':sort==='goals'?'Mål':view==='players'?'Poäng':'Räddningsprocent'}</SelectValue></SelectTrigger><SelectContent><SelectItem value="default">{view==='players'?'Poäng':'Räddningsprocent'}</SelectItem><SelectItem value="shots">Skott på mål</SelectItem>{view==='players'&&<SelectItem value="goals">Mål</SelectItem>}</SelectContent></Select></div></div><div className="players-controls"><TeamSelect label="Klubb" value={club} onChange={setClub} all/><label className="players-search"><span>Sök {view==='players'?'spelare':'målvakt'}</span><input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Namn"/></label></div>{view==='players'?<Rows heads={['Spelare','Lag','Matcher','Mål','Assist','Poäng','Skott på mål','Skotteffektivitet','+/−','Istid / match','xG']} rows={snapshot.players.filter(r=>(club==='all'||r.team===club)&&r.name.toLocaleLowerCase('sv').includes(query.toLocaleLowerCase('sv').trim())).sort((a,b)=>sort==='shots'?b.shots-a.shots:sort==='goals'?b.goals-a.goals:b.points-a.points||b.goals-a.goals).map(r=>[<ClubName team={r.team} name={r.name}/>,r.team,r.games,r.goals,r.assists,r.points,r.shots,r.shots?`${fmt(r.goals/r.shots*100,2)} %`:'—',r.plusMinus,r.toi,'—'])}/>:<Rows heads={['Målvakt','Lag','Matcher','Räddningar','Skott på mål','Räddningsprocent','Insläppta mål','GSAx']} rows={snapshot.goalies.filter(r=>(club==='all'||r.team===club)&&r.name.toLocaleLowerCase('sv').includes(query.toLocaleLowerCase('sv').trim())).sort((a,b)=>sort==='shots'?(b.saves+b.goals)-(a.saves+a.goals):(b.savePercentage??-1)-(a.savePercentage??-1)).map(r=>[<Dialog><DialogTrigger asChild><button className="text-button"><ClubName team={r.team} name={r.name}/><ChevronRight size={14}/></button></DialogTrigger><DialogContent className="ha-goalie-dialog"><DialogHeader><DialogTitle>{r.name} · match för match</DialogTitle><DialogDescription>{r.team} · Ordinarie tid utan tom målbur</DialogDescription></DialogHeader><GoalieLog games={games} name={r.name} team={r.team} open={open}/></DialogContent></Dialog>,r.team,r.games,r.saves,r.saves+r.goals,r.savePercentage===null?'—':`${fmt(r.savePercentage,2)} %`,r.goals,'—'])}/>}</section><p className="chart-note">Säsongssiffrorna kommer från ligans officiella statistik. Räddningsprocent = räddningar / (räddningar + insläppta mål). För matchstatistik, tryck på ett målvaktsnamn. xG och GSAx saknar underlag.</p></>}
 {view==='matches'&&<section className="panel"><div className="panel-heading"><div><h2>{team} · matcher</h2><p>Tryck på datumet för matchens statistik.</p></div></div>{matchList(selection(team))}</section>}
 {view==='compare'&&<><div className="ha-comparison-pickers"><TeamSelect label="Jämför med" value={second===team?HA_TEAMS.find(t=>t!==team)!:second} onChange={setSecond}/></div><div className="ha-compare-grid">{[team,second===team?HA_TEAMS.find(t=>t!==team)!:second].map(t=>{const s=summary(t);return <section className="panel" key={t}><h2><Club team={t}/></h2><Metrics items={[{label:'Mål',value:`${s.gf}–${s.ga}`,note:`${s.games} matcher`},{label:'Skotteffektivitet',value:s.shooting===null?'—':`${fmt(s.shooting,2)} %`,note:'Mål / skott på mål i urvalet'},{label:'xG',value:'—',note:'Skottpositioner saknas'}]}/></section>})}</div></>}
 {view==='data'&&<><section className="panel methodology"><span className="eyebrow">UNDERLAGET</span><h2>Hockeyallsvenskans officiella statistik.</h2><p>Riktiga resultat, spelare, målvakter och special teams från Hockeyallsvenskans publika tjänster.</p><div className="source-facts"><div><span>Säsong</span><strong>{snapshot.season}</strong></div><div><span>Spelade matcher</span><strong>{games.length}</strong></div><div><span>Data hämtade</span><strong>{new Date(snapshot.updatedAt).toLocaleString('sv-SE',{timeZone:'Europe/Stockholm'})}</strong></div></div><Missing/><p>Säsongsstatistik, slutresultat och matchernas officiella skott inkluderar förlängning. Matchlistor för spelare och målvakter avser ordinarie tid med båda målvakterna på isen. Special teams följer ligans officiella definition. Statistikurvalen kan därför skilja sig från varandra och från SHL:s xG-analys.</p><p>Data uppdateras gratis genom GitHub Actions efter matchkvällar, med en nattlig kontroll. Knappen läser den senast publicerade datafilen.</p><button className="button primary" onClick={onRefresh} disabled={syncing}><RefreshCw size={16}/>{syncing?'Läser data…':'Kontrollera publicerade uppdateringar'}</button>{message&&<p className="source-message" role="status">{message}</p>}<a className="text-link" href="https://hockeyallsvenskan.se/pages/statistik" target="_blank" rel="noreferrer">Hockeyallsvenskans statistik <ExternalLink size={14}/></a></section></>}
 </>;
}
function ClubName({team,name}:{team:string;name:string}){return <span className="league-team"><ClubLogo team={team} size={24} decorative/><strong>{name}</strong></span>}
