import {useEffect,useState} from 'react';
import {Info,ExternalLink} from 'lucide-react';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from './ui/table';
import {ClubLogo} from './club-logo';
import initial from '../data/special-teams.json';
import {efficiency,per60,specialTeamsNet,type SpecialTeamsSnapshot} from '../lib/special-teams';
const fmt=(v:number|null,d=1)=>v===null?'—':v.toLocaleString('sv-SE',{minimumFractionDigits:d,maximumFractionDigits:d});
const signed=(v:number|null)=>v===null?'—':`${v>0?'+':''}${fmt(v,2)}`;
const time=(v:number)=>`${Math.floor(v/60)}:${String(v%60).padStart(2,'0')}`;
export function SpecialTeams({team,league="shl",data:provided}:{team:string;league?:"shl"|"ha";data?:SpecialTeamsSnapshot}){
 const [stored,setSnapshot]=useState<SpecialTeamsSnapshot>(initial),[kind,setKind]=useState<'pp'|'pk'|'net'>('net');
 const snapshot=league==="ha"&&provided?provided:stored,leagueLabel=league==="ha"?"Hockeyallsvenskan":"SHL";
 useEffect(()=>{if(league!=="shl")return;const abort=new AbortController();fetch(new URL('data/special-teams.json',document.baseURI),{cache:'no-store',signal:abort.signal}).then(r=>r.ok?r.json():null).then(s=>{if(s?.season===initial.season&&s?.windows?.['all/all']?.rows?.length===14&&Date.parse(s.updatedAt)>Date.parse(initial.updatedAt))setSnapshot(s);}).catch(()=>{});return()=>abort.abort();},[league]);
 const data=snapshot.windows['all/all'];const own=data.rows.find(r=>r.team===team);
 const percent=(r:typeof data.rows[number])=>kind==='net'?specialTeamsNet(r):kind==='pp'?efficiency(r.ppGoals,r.ppChances):r.pkChances?100-efficiency(r.pkAgainst,r.pkChances)!:null;
 const rows=[...data.rows].sort((a,b)=>(percent(b)??-Infinity)-(percent(a)??-Infinity));
 return <><section className="filter-bar special-filter-bar" aria-label="Matchurval för special teams"><div><span className="filter-label">Matchurval</span><span className="special-period">Hela säsongen</span></div><p>Officiell {leagueLabel}-statistik · {snapshot.season}<br/>Till och med {snapshot.through}</p></section><div className="selection-context special-selection-context"><span>Hela säsongen · Hemma & borta</span><span>Inklusive förlängning och tom målbur enligt {leagueLabel}s definition</span></div>
 {own&&<><section className="team-heading"><div className="emblem-disc"><ClubLogo team={team} size={62} decorative/></div><div><h2>{team}</h2><p>{own.games} matcher <span>·</span> Powerplay & boxplay</p></div></section><section className="special-team-cards" aria-label="Lagets special teams"><article className="panel"><span className="eyebrow">Powerplay</span><h3>{fmt(efficiency(own.ppGoals,own.ppChances),2)}{own.ppChances?' %':''}</h3><p className="special-card-summary">{own.ppGoals} mål på {own.ppChances} överlägen</p><dl className="special-card-stats"><div><dt>Skott på mål</dt><dd>{own.ppShots}</dd></div><div><dt>Speltid</dt><dd>{time(own.ppSeconds)}</dd></div><div><dt>Mål / 60 min</dt><dd>{fmt(per60(own.ppGoals,own.ppSeconds),2)}</dd></div><div><dt>Skott / 60 min</dt><dd>{fmt(per60(own.ppShots,own.ppSeconds))}</dd></div><div><dt>Insläppta mål i eget PP</dt><dd>{own.ppAgainst}</dd></div></dl></article><article className="panel"><span className="eyebrow">Boxplay</span><h3>{fmt(own.pkChances?100-efficiency(own.pkAgainst,own.pkChances)!:null,2)}{own.pkChances?' %':''}</h3><p className="special-card-summary">{own.pkAgainst} insläppta mål på {own.pkChances} underlägen</p><dl className="special-card-stats"><div><dt>Skott på mål emot</dt><dd>{own.pkShotsAgainst}</dd></div><div><dt>Speltid</dt><dd>{time(own.pkSeconds)}</dd></div><div><dt>Insläppta mål / 60 min</dt><dd>{fmt(per60(own.pkAgainst,own.pkSeconds),2)}</dd></div><div><dt>Skott emot / 60 min</dt><dd>{fmt(per60(own.pkShotsAgainst,own.pkSeconds))}</dd></div><div><dt>Gjorda mål i eget BP</dt><dd>{own.pkGoals}</dd></div></dl></article><article className="panel"><span className="eyebrow">Special teams-netto</span><h3>{signed(specialTeamsNet(own))}<small className="special-unit">procentenheter</small></h3><p className="special-card-summary">{specialTeamsNet(own)===null?'Underlag saknas':specialTeamsNet(own)!>0?'Positivt netto':specialTeamsNet(own)!<0?'Negativt netto':'Neutralt netto'}</p><div className="special-net-explainer"><p>Powerplay % + boxplay % − 100</p><p>0 är neutralt. Plus betyder högre målfrekvens i PP än insläppsfrekvens i BP.</p><p>Exempel: 25 % powerplay + 80 % boxplay − 100 = +5 procentenheter.</p><p>Mål i eget boxplay och insläppta mål i eget powerplay ingår inte.</p></div></article></section></>}
 <section className="panel"><div className="panel-heading"><div><h3>Jämför hela {leagueLabel}</h3><p>Sorterat efter {kind==='net'?'special teams-netto':kind==='pp'?'PP-effektivitet':'andel klarade boxplay'}</p></div><div className="table-mode"><button className={kind==='net'?'active':''} onClick={()=>setKind('net')}>Netto</button><button className={kind==='pp'?'active':''} onClick={()=>setKind('pp')}>Powerplay</button><button className={kind==='pk'?'active':''} onClick={()=>setKind('pk')}>Boxplay</button></div></div><Table className="xg-table"><TableHeader><TableRow>{(kind==='net'?['Lag','Matcher','Netto (procentenheter)','PP %','BP %']:['Lag','Matcher',kind==='pp'?'PP %':'BP %',kind==='pp'?'PP-mål':'Insläppta PP-mål','Tillfällen',kind==='pp'?'Skott på mål':'Skott emot','Speltid',kind==='pp'?'Mål / 60 min':'Insläppta / 60 min',kind==='pp'?'Skott / 60 min':'Skott emot / 60 min']).map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.map(r=><TableRow key={r.team} className={r.team===team?'selected-row':''}><TableCell><span className="league-team"><ClubLogo team={r.team} size={24} decorative/>{r.team}</span></TableCell><TableCell>{r.games}</TableCell><TableCell>{kind==='net'?signed(specialTeamsNet(r)):`${fmt(percent(r),2)} %`}</TableCell>{kind==='net'?<><TableCell>{fmt(efficiency(r.ppGoals,r.ppChances),2)} %</TableCell><TableCell>{fmt(r.pkChances?100-efficiency(r.pkAgainst,r.pkChances)!:null,2)} %</TableCell></>:<><TableCell>{kind==='pp'?r.ppGoals:r.pkAgainst}</TableCell><TableCell>{kind==='pp'?r.ppChances:r.pkChances}</TableCell><TableCell>{kind==='pp'?r.ppShots:r.pkShotsAgainst}</TableCell><TableCell>{time(kind==='pp'?r.ppSeconds:r.pkSeconds)}</TableCell><TableCell>{fmt(per60(kind==='pp'?r.ppGoals:r.pkAgainst,kind==='pp'?r.ppSeconds:r.pkSeconds),2)}</TableCell><TableCell>{fmt(per60(kind==='pp'?r.ppShots:r.pkShotsAgainst,kind==='pp'?r.ppSeconds:r.pkSeconds))}</TableCell></>}</TableRow>)}</TableBody></Table></section>
 <section className="model-note"><Info size={18}/><p><strong>Hur beräknas special teams?</strong><span>Officiellt säsongsunderlag till och med {snapshot.through}. Uppdaterat {new Date(snapshot.updatedAt).toLocaleString('sv-SE')}. Urvalet inkluderar förlängning och tom målbur enligt {leagueLabel}s definition och skiljer sig därför från xG-analysens urval.</span><span>PP % = mål i powerplay / antal numerära överlägen. BP % = 1 − insläppta powerplaymål / antal numerära underlägen. Mått per 60 minuter använder faktisk PP- respektive BP-speltid. Noll tillfällen eller ingen speltid visas som —. Små urval påverkar jämförelsen.</span><span>Special teams-netto = PP % + BP % − 100, uttryckt i procentenheter. 0 är neutralt, plus är positivt och minus negativt. Detta är ett frekvensmått, inte målskillnad eller en jämförelse med ligasnittet. Både PP- och BP-tillfällen krävs.</span><span>xG per spelform och 5 mot 5 är ännu inte verifierade. PP- och BP-siffrorna är officiell statistik, inte uppskattningar från utvisningar.</span><span><a href={league==="ha"?"https://hockeyallsvenskan.se/pages/statistik":"https://www.shl.se/game-stats/teams/powerplay"} target="_blank" rel="noreferrer">Powerplay hos {leagueLabel} <ExternalLink size={13}/></a> · <a href={league==="ha"?"https://hockeyallsvenskan.se/pages/statistik":"https://www.shl.se/game-stats/teams/penaltyKilling"} target="_blank" rel="noreferrer">Boxplay hos {leagueLabel} <ExternalLink size={13}/></a></span></p></section></>;
}
