import {useEffect,useState} from 'react';
import {Info,ExternalLink} from 'lucide-react';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from './ui/table';
import {ClubLogo} from './club-logo';
import initial from '../data/special-teams.json';
import {efficiency,per60,specialTeamsNet,type SpecialTeamsSnapshot} from '../lib/special-teams';
const fmt=(v:number|null,d=1)=>v===null?'—':v.toLocaleString('sv-SE',{minimumFractionDigits:d,maximumFractionDigits:d});
const signed=(v:number|null)=>v===null?'—':`${v>0?'+':''}${fmt(v,2)} pp`;
const time=(v:number)=>`${Math.floor(v/60)}:${String(v%60).padStart(2,'0')}`;
export function SpecialTeams({team}:{team:string}){
 const [snapshot,setSnapshot]=useState<SpecialTeamsSnapshot>(initial),[kind,setKind]=useState<'pp'|'pk'|'net'>('net');
 useEffect(()=>{const abort=new AbortController();fetch(new URL('data/special-teams.json',document.baseURI),{cache:'no-store',signal:abort.signal}).then(r=>r.ok?r.json():null).then(s=>{if(s?.season===initial.season&&s?.windows?.['all/all']?.rows?.length===14&&Date.parse(s.updatedAt)>Date.parse(initial.updatedAt))setSnapshot(s);}).catch(()=>{});return()=>abort.abort();},[]);
 const data=snapshot.windows['all/all'];const own=data.rows.find(r=>r.team===team);
 const percent=(r:typeof data.rows[number])=>kind==='net'?specialTeamsNet(r):kind==='pp'?efficiency(r.ppGoals,r.ppChances):r.pkChances?100-efficiency(r.pkAgainst,r.pkChances)!:null;
 const rows=[...data.rows].sort((a,b)=>(percent(b)??-Infinity)-(percent(a)??-Infinity));
 return <><section className="panel"><div className="panel-heading"><div><h2>Powerplay & boxplay</h2><p>Officiell SHL-statistik · {snapshot.season} · Hela säsongen till och med {snapshot.through} · Hemma & borta</p></div></div><div className="inline-info"><Info size={18}/><p>Den här vyn omfattar hela säsongen, inklusive förlängning och tom målbur enligt källans definition. Den har ett annat urval än Isbilds xG-analys. Uppdaterad {new Date(snapshot.updatedAt).toLocaleString('sv-SE')}.</p></div></section>
 {own&&<section className="performance-factors special-team-cards"><article className="panel"><span className="eyebrow">{team} · Powerplay</span><h3>{fmt(efficiency(own.ppGoals,own.ppChances),2)} %</h3><p>{own.ppGoals} mål på {own.ppChances} numerära överlägen · {own.games} matcher</p><p>{own.ppShots} skott på mål · {time(own.ppSeconds)} speltid</p><p>{fmt(per60(own.ppGoals,own.ppSeconds),2)} mål / 60 min · {fmt(per60(own.ppShots,own.ppSeconds))} skott / 60 min</p><p>{own.ppAgainst} insläppta mål i eget powerplay</p></article><article className="panel"><span className="eyebrow">{team} · Boxplay</span><h3>{fmt(own.pkChances?100-efficiency(own.pkAgainst,own.pkChances)!:null,2)} %</h3><p>{own.pkAgainst} insläppta mål på {own.pkChances} numerära underlägen · {own.games} matcher</p><p>{own.pkShotsAgainst} skott på mål emot · {time(own.pkSeconds)} speltid</p><p>{fmt(per60(own.pkAgainst,own.pkSeconds),2)} insläppta mål / 60 min · {fmt(per60(own.pkShotsAgainst,own.pkSeconds))} skott emot / 60 min</p><p>{own.pkGoals} gjorda mål i eget boxplay</p></article><article className="panel"><span className="eyebrow">{team} · Special teams-netto</span><h3>{signed(specialTeamsNet(own))}</h3><p>{specialTeamsNet(own)===null?'Underlag saknas':specialTeamsNet(own)!>0?'Positivt netto':specialTeamsNet(own)!<0?'Negativt netto':'Neutralt netto'}</p><p>PP % + BP % − 100 · procentenheter</p><p>0 är neutralt. Plus betyder högre målfrekvens i PP än insläppsfrekvens i BP.</p><p>Måttet väger frekvenser lika och är inte faktisk målskillnad. Mål i eget boxplay och insläppta i eget PP ingår inte.</p></article></section>}
 <section className="panel"><div className="panel-heading"><div><h3>Jämför hela SHL</h3><p>Sorterat efter {kind==='net'?'special teams-netto':kind==='pp'?'PP-effektivitet':'andel klarade boxplay'}</p></div><div className="table-mode"><button className={kind==='net'?'active':''} onClick={()=>setKind('net')}>Netto</button><button className={kind==='pp'?'active':''} onClick={()=>setKind('pp')}>Powerplay</button><button className={kind==='pk'?'active':''} onClick={()=>setKind('pk')}>Boxplay</button></div></div><Table className="xg-table"><TableHeader><TableRow>{(kind==='net'?['Lag','Matcher','Netto (pp)','PP %','BP %']:['Lag','Matcher',kind==='pp'?'PP %':'BP %',kind==='pp'?'PP-mål':'Insläppta PP-mål','Tillfällen',kind==='pp'?'Skott på mål':'Skott emot','Speltid',kind==='pp'?'Mål / 60 min':'Insläppta / 60 min',kind==='pp'?'Skott / 60 min':'Skott emot / 60 min']).map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.map(r=><TableRow key={r.team} className={r.team===team?'selected-row':''}><TableCell><span className="league-team"><ClubLogo team={r.team} size={24} decorative/>{r.team}</span></TableCell><TableCell>{r.games}</TableCell><TableCell>{kind==='net'?signed(specialTeamsNet(r)):`${fmt(percent(r),2)} %`}</TableCell>{kind==='net'?<><TableCell>{fmt(efficiency(r.ppGoals,r.ppChances),2)} %</TableCell><TableCell>{fmt(r.pkChances?100-efficiency(r.pkAgainst,r.pkChances)!:null,2)} %</TableCell></>:<><TableCell>{kind==='pp'?r.ppGoals:r.pkAgainst}</TableCell><TableCell>{kind==='pp'?r.ppChances:r.pkChances}</TableCell><TableCell>{kind==='pp'?r.ppShots:r.pkShotsAgainst}</TableCell><TableCell>{time(kind==='pp'?r.ppSeconds:r.pkSeconds)}</TableCell><TableCell>{fmt(per60(kind==='pp'?r.ppGoals:r.pkAgainst,kind==='pp'?r.ppSeconds:r.pkSeconds),2)}</TableCell><TableCell>{fmt(per60(kind==='pp'?r.ppShots:r.pkShotsAgainst,kind==='pp'?r.ppSeconds:r.pkSeconds))}</TableCell></>}</TableRow>)}</TableBody></Table></section>
 <section className="model-note"><Info size={18}/><p><strong>Hur beräknas special teams?</strong><span>PP % = mål i powerplay / antal numerära överlägen. BP % = 1 − insläppta powerplaymål / antal numerära underlägen. Mått per 60 minuter använder faktisk PP- respektive BP-speltid. Noll tillfällen eller ingen speltid visas som —. Små urval påverkar jämförelsen.</span><span>Special teams-netto = PP % + BP % − 100, uttryckt i procentenheter (pp). 0 är neutralt, plus är positivt och minus negativt. Detta är ett frekvensmått, inte målskillnad eller en jämförelse med ligasnittet. Både PP- och BP-tillfällen krävs.</span><span>xG per spelform och 5 mot 5 är ännu inte verifierade. PP- och BP-siffrorna är officiell statistik, inte uppskattningar från utvisningar.</span><span><a href="https://www.shl.se/game-stats/teams/powerplay" target="_blank" rel="noreferrer">Powerplay hos SHL <ExternalLink size={13}/></a> · <a href="https://www.shl.se/game-stats/teams/penaltyKilling" target="_blank" rel="noreferrer">Boxplay hos SHL <ExternalLink size={13}/></a></span></p></section></>;
}
