import {aggregate,teamGames} from './analysis.ts';
import {perspective,result,type Game,type Scope} from './hockey.ts';
import type {Shot} from './shl.ts';
export function distribution(probabilities:number[]){let d=[1];for(const p of probabilities){if(!Number.isFinite(p)||p<0||p>1)throw Error('Invalid probability');const next=Array(d.length+1).fill(0);d.forEach((v,k)=>{next[k]+=v*(1-p);next[k+1]+=v*p;});d=next;}return d;}
// A rebound chain can produce at most one goal: later shots depend on earlier misses.
export function chanceGroups(shots:Shot[]){const groups:{home:boolean;last:number;period:number;survival:number}[]=[];for(const s of shots.filter(s=>s.eligible&&!s.emptyNet&&s.period<=3&&s.outcome!=='blocked').sort((a,b)=>a.seconds-b.seconds)){if(s.xg==null||!Number.isFinite(s.xg)||s.xg<0||s.xg>1)return null;const last=groups.at(-1);if(s.rebound&&last&&last.home===s.home&&last.period===s.period&&s.seconds-last.last<=3){last.survival*=1-s.xg;last.last=s.seconds;}else groups.push({home:s.home,last:s.seconds,period:s.period,survival:1-s.xg});}return groups;}
export function expectedOutcome(game:Game){if(!game.shots?.length||!game.stats.all)return null;const shots=game.shots.filter(s=>s.eligible&&!s.emptyNet&&s.period<=3);if(Math.abs(shots.filter(s=>s.home).reduce((a,s)=>a+(s.xg??NaN),0)-game.stats.all.xgf)>1e-6||Math.abs(shots.filter(s=>!s.home).reduce((a,s)=>a+(s.xg??NaN),0)-game.stats.all.xga)>1e-6)return null;const groups=chanceGroups(shots);if(!groups?.length)return null;const h=distribution(groups.filter(g=>g.home).map(g=>1-g.survival)),a=distribution(groups.filter(g=>!g.home).map(g=>1-g.survival));let win=0,draw=0,loss=0;h.forEach((p,i)=>a.forEach((q,j)=>{if(i>j)win+=p*q;else if(i===j)draw+=p*q;else loss+=p*q;}));return {homeWin:win,draw,awayWin:loss,homePoints:3*win+1.5*draw,awayPoints:3*loss+1.5*draw,homeOverallWin:win+.5*draw};}
export function expectedTable(games:Game[]){const rows=new Map<string,{team:string;played:number;points:number;actual:number;xgf:number;xga:number}>();let missing=0;for(const g of games){const out=expectedOutcome(g);if(!out){missing++;continue;}for(const home of [true,false]){const team=home?g.home:g.away;let r=rows.get(team);if(!r){r={team,played:0,points:0,actual:0,xgf:0,xga:0};rows.set(team,r);}r.played++;r.points+=home?out.homePoints:out.awayPoints;r.actual+=result(g,team).points;r.xgf+=home?g.stats.all!.xgf:g.stats.all!.xga;r.xga+=home?g.stats.all!.xga:g.stats.all!.xgf;}}return {rows:[...rows.values()].sort((a,b)=>b.points-a.points||(b.xgf-b.xga)-(a.xgf-a.xga)||a.team.localeCompare(b.team,'sv')),missing};}
export function profile(games:Game[],team:string,scope:Scope='all'){const usable=games.filter(g=>perspective(g,team,scope)),s=aggregate(usable,team,scope);const minutes=usable.every(g=>typeof perspective(g,team,scope)!.minutes==='number'&&perspective(g,team,scope)!.minutes!>0)?usable.reduce((a,g)=>a+perspective(g,team,scope)!.minutes!,0):null;const attempts=usable.flatMap(g=>(g.shots||[]).filter(x=>x.eligible&&x.period<=3&&!x.emptyNet&&x.outcome!=='blocked'&&(scope==='all'||(scope==='five'?x.strength==='five':x.strength===(g.home===team?scope:scope==='pp'?'pk':'pp')))));const forShots=attempts.filter(x=>x.home===(games.find(g=>g.shots?.includes(x))?.home===team));const against=attempts.filter(x=>!forShots.includes(x));const coverage=scope==='all'&&usable.every(g=>g.shots?.length);return {s,minutes,unit:minutes?'per 60 min':'per match',forRate:s.n?s.xgf/(minutes?minutes/60:s.n):null,againstRate:s.n?s.xga/(minutes?minutes/60:s.n):null,forVolume:coverage?forShots.length/s.n:null,againstVolume:coverage?against.length/s.n:null,forQuality:coverage&&forShots.length?s.xgf/forShots.length:null,againstQuality:coverage&&against.length?s.xga/against.length:null};}
export function zoneProfile(games:Game[],team:string){const rows=['Nära mål (< 5 m)','Mellan (5–10 m)','Långt (> 10 m)'].map(label=>({label,forShots:0,againstShots:0,xgf:0,xga:0}));for(const g of games)for(const s of g.shots||[]){if(!s.eligible||s.emptyNet||s.period>3||s.outcome==='blocked'||s.xg==null)continue;const distance=Math.hypot(s.x*.0925,s.y*.1003846154),r=rows[distance<5?0:distance<=10?1:2];if(s.home===(g.home===team)){r.forShots++;r.xgf+=s.xg;}else{r.againstShots++;r.xga+=s.xg;}}return rows;}
export function windowComparison(games:Game[],team:string,venue:string,scope:Scope,size=5){const all=teamGames(games,team,'all',venue).filter(g=>perspective(g,team,scope)),current=all.slice(-size),previous=all.slice(-2*size,-size);const a=aggregate(current,team,scope),b=aggregate(previous,team,scope),diffs=current.map(g=>{const s=perspective(g,team,scope)!;return s.xgf-s.xga;});return {current,previous,a,b,complete:current.length===size&&previous.length===size,best:diffs.length?Math.max(...diffs):null,worst:diffs.length?Math.min(...diffs):null,positive:diffs.filter(v=>v>0).length};}
export function scoreContext(games:Game[],team:string){const rows=['Lika','Ledning','Underläge'].map(label=>({label,shots:0,xgf:0,xga:0}));let missing=0;for(const g of games){if(!g.goals){missing++;continue;}const goals=g.goals.filter(e=>e.seconds<=3600&&e.reason!=='Förlängning');for(const s of g.shots||[]){if(!s.eligible||s.emptyNet||s.period>3||s.outcome==='blocked'||s.xg==null)continue;let h=0,a=0;for(const goal of goals){if(goal.seconds<s.seconds||(goal.seconds===s.seconds&&goal.id!==s.id&&g.shots!.findIndex(x=>x.id===goal.id)>=0&&g.shots!.findIndex(x=>x.id===goal.id)<g.shots!.indexOf(s))){if(goal.home)h++;else a++;}}if(s.scoreBeforeHome!==undefined&&s.scoreBeforeAway!==undefined){h=s.scoreBeforeHome;a=s.scoreBeforeAway;}const diff=g.home===team?h-a:a-h,r=rows[diff===0?0:diff>0?1:2];r.shots++;if(s.home===(g.home===team))r.xgf+=s.xg;else r.xga+=s.xg;}}return {rows,missing};}
export function opponents(games:Game[],selection:Game[],team:string){const names=[...new Set(selection.map(g=>g.home===team?g.away:g.home))];return names.map(opponent=>{const own=selection.filter(g=>g.home===opponent||g.away===opponent);const rest=games.filter(g=>(g.home===opponent||g.away===opponent)&&g.home!==team&&g.away!==team);return {team:opponent,met:own.length,reference:aggregate(rest,opponent,'all')};}).sort((a,b)=>(b.reference.share??-1)-(a.reference.share??-1));}
