export const HA_NAMES:Record<string,string>={AIK:'AIK',AIS:'Almtuna IS',BIK:'BIK Karlskoga',IKO:'IK Oskarshamn',KHC:'Kalmar HC',LIF:'Leksands IF',MIK:'Mora IK',MORA:'Mora IK',MODO:'MoDo Hockey',NYB:'Nybro Vikings',NVIF:'Nybro Vikings',OSIK:'Östersund IK','ÖIK':'Östersund IK',SSK:'Södertälje SK',VHC:'Vimmerby Hockey',VIK:'Västerås IK',VIS:'Visby Roma HK'};
export const HA_TEAMS=[...new Set(Object.values(HA_NAMES))].sort((a,b)=>a.localeCompare(b,'sv'));
export const haName=(code:string)=>{const name=HA_NAMES[code?.toUpperCase()];if(!name)throw Error(`Unknown Hockeyallsvenskan club: ${code}`);return name;};
export type HaPlayer={name:string;team:string;games:number;goals:number;assists:number;points:number;shots:number;plusMinus:number;toi:string};
export type HaGoalie={name:string;team:string;games:number;saves:number;goals:number;savePercentage:number|null};
export type HaGame={id:string;date:string;home:string;away:string;resultHome:number;resultAway:number;decided:string;homeShots:number|null;awayShots:number|null;url:string;fetchedAt?:string;players?:{name:string;team:string;goals:number;firstAssists:number;secondAssists:number;shots:number;attempts:number}[];goalies?:HaGoalie[];eventCoverage?:string};
export type HaTeam={team:string;games:number;goals:number;shots:number;corsi:number|null;fenwick:number|null;pdo:number|null};
export type HaSnapshot={league:'ha';season:string;updatedAt:string;games:HaGame[];players:HaPlayer[];goalies:HaGoalie[];teams:HaTeam[];special:import('./special-teams').SpecialTeamsSnapshot;sources:string[];coverage:{coordinates:false;xg:false;gsax:false}};
function count(v:unknown){if(typeof v!=='number'||!Number.isInteger(v)||v<0)throw Error('Invalid official HA count');return v;}
function pct(v:unknown){if(v===null||v===undefined||v==='')return null;const n=Number(v);if(!Number.isFinite(n)||n<0||n>100)throw Error('Invalid percentage');return n;}
function time(v:string){if(!/^\d+(?::\d{2}){1,2}$/.test(v))throw Error('Invalid official time');const parts=v.split(':').map(Number);if(parts.slice(1).some(n=>n>59))throw Error('Invalid seconds');return parts.reduce((n,v)=>n*60+v,0);}
export function haStandings(games:HaGame[]){return HA_TEAMS.map(team=>{const selected=games.filter(g=>g.home===team||g.away===team);return selected.reduce((r,g)=>{const h=g.home===team,gf=h?g.resultHome:g.resultAway,ga=h?g.resultAway:g.resultHome,w=gf>ga,ot=g.decided!=='FT';r.games++;r.gf+=gf;r.ga+=ga;r.points+=w?(ot?2:3):(ot?1:0);r.wins+=w?1:0;return r;},{team,games:0,gf:0,ga:0,points:0,wins:0});}).sort((a,b)=>b.points-a.points||(b.gf-b.ga)-(a.gf-a.ga)||b.gf-a.gf||a.team.localeCompare(b.team,'sv'));}
export function parseHaSnapshot(input:{games:any;players:any;goalies:any;offensive:any;corsi:any;pp:any;pk:any},updatedAt:string):HaSnapshot{
 const raw=input.games;if(!Array.isArray(raw.results)||raw.results.length!==raw.count||raw.total_pages!==1||raw.count<1)throw Error('Incomplete HA games');
 const games:HaGame[]=raw.results.map((g:any)=>{const home=haName(g.HomeTeam),away=haName(g.AwayTeam);if(home===away||!/^\d{4}-\d{2}-\d{2}$/.test(g.Date)||!['FT','OT','SO'].includes(g.decided_in))throw Error('Invalid completed game');const h=count(g.GameResult?.Home),a=count(g.GameResult?.Away);if(h===a)throw Error('Completed game lacks winner');const shots=(side:string)=>{const v=g.GameStatistics?.[side]?.shots?.total;return v===undefined?null:count(v);};return {id:`ha-${g.Date}-${g.HomeTeam.toLowerCase()}-${g.AwayTeam.toLowerCase()}`,date:g.Date,home,away,resultHome:h,resultAway:a,decided:g.decided_in,homeShots:shots('home_team'),awayShots:shots('away_team'),url:'https://hockeyallsvenskan.se/pages/statistik'};});if(new Set(games.map(g=>g.id)).size!==games.length)throw Error('Duplicate HA game');
 const standings=haStandings(games);const maps=[input.offensive,input.corsi,input.pp,input.pk].map(p=>{if(!Array.isArray(p.data)||p.data.length!==14)throw Error('Incomplete HA teams');const map=new Map(p.data.map((r:any)=>[haName(r.team_code),r]));if(map.size!==14)throw Error('Duplicate HA club');return map as Map<string,any>;});
 const [off,cor,pp,pk]=maps;for(const r of standings)for(const map of maps)if(count(map.get(r.team)?.GP)!==r.games)throw Error('HA match selection mismatch');
 const teams=standings.map(r=>{const o=off.get(r.team),c=cor.get(r.team);if(count(o.G)!==r.gf)throw Error('HA goals mismatch');return {team:r.team,games:r.games,goals:r.gf,shots:count(o.SOG),corsi:pct(c.Corsi?.CF_perc),fenwick:pct(c.Fenwick?.FF_perc),pdo:c.PDO?.PDO==null?null:Number(c.PDO.PDO)};});
 const rows=standings.map(r=>{const p=pp.get(r.team).PowerPlay,k=pk.get(r.team).PenaltyKill;const row={team:r.team,games:r.games,ppGoals:count(p.PPG),ppAgainst:count(p.GA),ppChances:count(p.OPP),ppShots:count(p.PPSOG),ppSeconds:time(p.TPP),pkGoals:count(k.G),pkAgainst:count(k.GA),pkChances:count(k.OPP),pkShotsAgainst:count(k.SOGA),pkSeconds:time(k.TSH)};for(const [value,expected] of [[p.PP_perc,row.ppChances?row.ppGoals/row.ppChances*100:0],[k.PK_perc,row.pkChances?(1-row.pkAgainst/row.pkChances)*100:0]])if(Math.abs(Number(value)-expected)>.011)throw Error('HA PP/BP percentage mismatch');return row;});
 for(const [a,b] of [['ppGoals','pkAgainst'],['ppAgainst','pkGoals'],['ppChances','pkChances'],['ppShots','pkShotsAgainst']] as const)if(rows.reduce((n,r)=>n+r[a],0)!==rows.reduce((n,r)=>n+r[b],0))throw Error('HA special teams league mismatch');
 const individuals=(p:any)=>{if(!Array.isArray(p.results)||p.results.length!==p.count||p.total_pages!==1)throw Error('Incomplete HA individuals');const keys=new Set();for(const r of p.results){const team=haName(r.team),key=team+'|'+r.player;if(typeof r.player!=='string'||!r.player.trim()||keys.has(key)||count(r.GP)>standings.find(s=>s.team===team)!.games)throw Error('Invalid HA individual');keys.add(key);}return p.results;};
 const players=individuals(input.players).map((r:any)=>({name:r.player,team:haName(r.team),games:count(r.GP),goals:count(r.G),assists:count(r.A),points:count(r.TP),shots:count(r.SOG),plusMinus:Number(r.PlusMinus),toi:r.TOI_GP}));
 const goalies=individuals(input.goalies).map((r:any)=>{const saves=count(r.SVS),goals=count(r.GA),reported=pct(r.SVS_perc),sv=saves+goals?saves/(saves+goals)*100:null;if(sv!==null&&reported!==null&&Math.abs(sv-reported)>.011)throw Error('HA save percentage mismatch');return {name:r.player,team:haName(r.team),games:count(r.GPI),saves,goals,savePercentage:sv};});
 const through=games.map(g=>g.date).sort().at(-1)!;return {league:'ha',season:'2026/27',updatedAt,games,players,goalies,teams,special:{season:'2026/27',updatedAt,through,windows:{'all/all':{rows,sources:['https://hockeyallsvenskan.se/pages/statistik']}}},sources:['https://hockeyallsvenskan.se/pages/statistik','https://hockeyallsvenskan.se/pages/matcher'],coverage:{coordinates:false,xg:false,gsax:false}};
}
// Separate regulation sample; the public feed supplies no shot coordinates.
export function haMatchEvents(payload:any,homeCode:string,awayCode:string){if(payload?.game_info?.game_finished!==true||!Array.isArray(payload.game_events))throw Error('Incomplete HA events');const home=haName(homeCode),away=haName(awayCode),keepers:Record<string,string|null|undefined>={},goalies=new Map<string,HaGoalie>(),players=new Map<string,NonNullable<HaGame['players']>[number]>();let unknown=0;
 const player=(name:string,team:string)=>{const key=team+'|'+name;let r=players.get(key);if(!r){r={name,team,goals:0,firstAssists:0,secondAssists:0,shots:0,attempts:0};players.set(key,r);}return r;};
 for(const period of payload.game_events){if(Number(period.Period)<1||Number(period.Period)>3)continue;for(const e of period.Events){const team=haName(e.team.statNetId||e.team.code);if(team!==home&&team!==away)throw Error('Wrong team in HA feed');const name=e.player?[e.player.firstName,e.player.familyName].filter(Boolean).join(' ').trim():'';if(e.type==='GoalkeeperEvent'){if(typeof e.isEntering!=='boolean')throw Error('Unknown keeper event');keepers[team]=e.isEntering?name||undefined:null;continue;}if(!['Shot','Goal'].includes(e.type)||e.isPenaltyShot===true||e.isPenaltyShot==='true')continue;if(keepers[home]===null||keepers[away]===null)continue;if(!keepers[home]||!keepers[away]){unknown++;continue;}const goal=e.type==='Goal',saved=e.eventDescription==='save';if(name){const r=player(name,team);r.attempts++;if(goal||saved)r.shots++;if(goal)r.goals++;}if(goal){for(const [field,key] of [['Assist1','firstAssists'],['Assist2','secondAssists']] as const)if(e[field]?.name)player(e[field].name,team)[key]++;}if(goal||saved){const defending=team===home?away:home,keeper=keepers[defending]!,key=defending+'|'+keeper;let r=goalies.get(key);if(!r){r={name:keeper,team:defending,games:1,saves:0,goals:0,savePercentage:null};goalies.set(key,r);}if(goal)r.goals++;else r.saves++;}}}
 if(unknown)return {players:[],goalies:[],eventCoverage:'Målvaktsidentitet saknas för delar av matchen. Matchstatistik visas inte.'};for(const r of goalies.values())r.savePercentage=r.saves+r.goals?r.saves/(r.saves+r.goals)*100:null;return {players:[...players.values()],goalies:[...goalies.values()],eventCoverage:'Ordinarie tid med båda målvakterna på isen. Inga skottpositioner i källan.'};}
