import type {Game,Stat} from './hockey';
export type ShlScheduleGame={uuid:string;state:string;startDateTime:string;rawStartDateTime:string;overtime:boolean;shootout:boolean;ssgtUuid:string;homeTeamInfo:{code:string;score:number;names:{full:string}};awayTeamInfo:{code:string;score:number;names:{full:string}}};
export type ShlEvent={eventId?:number;eventUuid?:string;revision?:number;type:string;period:number;time?:string;realWorldTime?:string;eventTeam?:{place:string;teamCode:string};locationX?:number;locationY?:number;goalSection?:number;isPenaltyShot?:boolean;isEmptyNetGoal?:boolean;isEntering?:boolean;goalStatus?:string;player?:{firstName:string;familyName:string};homeTeam?:{score:number};awayTeam?:{score:number}};
export type Shot={id:string;seconds:number;period:number;home:boolean;x:number;y:number;outcome:'goal'|'saved'|'missed'|'blocked';player:string;rebound:boolean;eligible:boolean;emptyNet:boolean;strength?:string;xg?:number};
export type XgModel={name:string;features:string[];mean:number[];scale:number[];coefficients:number[];intercept:number;validation:Record<string,unknown>;trainedAt:string};
export const SHL_SEASON='2026/27';
export const SHL_SCHEDULE_URL='https://www.shl.se/api/sports-v2/game-schedule?seasonUuid=ndcf81nlb3&seriesUuid=qQ9-bb0bzEWUk&gameTypeUuid=qQ9-af37Ti40B&gamePlace=all&played=all';
export const sourceUrl=(id:string)=>`https://www.shl.se/api/gameday/play-by-play/${id}`;
export const nameByCode:Record<string,string>={DIF:'Djurgårdens IF',BIF:'Brynäs IF',FBK:'Färjestad BK',FHC:'Frölunda HC',HV71:'HV71',IFB:'Björklöven',LHC:'Linköping HC',LHF:'Luleå Hockey',MIF:'Malmö Redhawks','ÖRE':'Örebro Hockey',OHK:'Örebro Hockey',RBK:'Rögle BK',SKE:'Skellefteå AIK',SAIK:'Skellefteå AIK',TIK:'Timrå IK',VLH:'Växjö Lakers',LIF:'Leksands IF'};
export function clock(e:ShlEvent){if(!e.time||!/^\d{2}:\d{2}$/.test(e.time))return null;const [m,s]=e.time.split(':').map(Number);if(m>20||s>59)return null;return (e.period-1)*1200+m*60+s;}
export function extractShots(input:ShlEvent[]):Shot[]{const dedup=new Map<string,ShlEvent>();for(const e of input){const id=e.eventUuid||String(e.eventId??`${e.type}-${e.period}`);const old=dedup.get(id);if(!old||(e.revision||0)>=(old.revision||0))dedup.set(id,e);}const events=[...dedup.values()].filter(e=>e.period>=1&&e.period<=3&&clock(e)!==null).sort((a,b)=>clock(a)!-clock(b)!||(a.realWorldTime||'').localeCompare(b.realWorldTime||'')||(a.eventId||0)-(b.eventId||0));const keepers:{home:boolean|null;away:boolean|null}={home:null,away:null};let last:Shot|undefined;const shots:Shot[]=[];
 for(const e of events){const side=e.eventTeam?.place;if(side!=='home'&&side!=='away')continue;if(e.type==='goalkeeper'){keepers[side]=e.isEntering===true;continue;}if(e.type!=='goal'&&e.type!=='shot')continue;if(e.isPenaltyShot||e.goalSection===-2)continue;const sec=clock(e)!;if(sec>3600)continue;if(typeof e.locationX!=='number'||typeof e.locationY!=='number'||!Number.isFinite(e.locationX)||!Number.isFinite(e.locationY)||e.locationX< -60||e.locationX>650||Math.abs(e.locationY)>170)throw Error('Skottposition saknas eller har ändrat format.');const home=side==='home';const outcome=e.type==='goal'?'goal':e.goalSection===-3?'blocked':e.goalSection!==undefined&&e.goalSection>0?'saved':'missed';const empty=e.isEmptyNetGoal===true||keepers.home===false||keepers.away===false;const eligible=!empty&&keepers.home===true&&keepers.away===true;const shot:Shot={id:e.eventUuid||String(e.eventId),seconds:sec,period:e.period,home,x:e.locationX,y:e.locationY,outcome,player:e.player?`${e.player.firstName} ${e.player.familyName}`:'Okänd spelare',rebound:!!(last&&last.home===home&&last.period===e.period&&sec-last.seconds>=0&&sec-last.seconds<=3&&last.outcome!=='goal'&&last.outcome!=='blocked'),eligible,emptyNet:empty,strength:e.goalStatus};shots.push(shot);last=shot;}
 return shots;
}
export function goalEvents(input:ShlEvent[]){const ids=new Map<string,ShlEvent>();for(const e of input){if(e.type!=='goal'||typeof e.period!=='number'||e.period<1||e.period>4)continue;const id=e.eventUuid||String(e.eventId);const old=ids.get(id);if(!old||(e.revision||0)>=(old.revision||0))ids.set(id,e);}const shots=extractShots(input);return [...ids.entries()].map(([id,e])=>{const shot=shots.find(s=>s.id===id);const included=!!shot?.eligible;const reason=e.period>3?'Förlängning':e.isPenaltyShot?'Straffslag':shot?.emptyNet||e.isEmptyNetGoal?'Uttagen målvakt':included?'Ingår i analysen':'Utanför analysen';return {id,seconds:clock(e)??0,home:e.eventTeam?.place==='home',player:e.player?`${e.player.firstName} ${e.player.familyName}`:'Okänd spelare',included,reason};}).sort((a,b)=>a.seconds-b.seconds);}
export function features(s:Shot){const x=s.x*.0925,y=s.y*.1003846154,d=Math.hypot(x,y),angle=Math.atan2(Math.abs(y),x);return [d/10,d*d/1000,angle/(Math.PI/2),y*y/1000,s.rebound?1:0];}
export function probability(s:Shot,model:XgModel){if(s.outcome==='blocked')return 0;const x=features(s);let logit=model.intercept;model.coefficients.forEach((c,i)=>{logit+=c*((x[i]-model.mean[i])/model.scale[i]);});return 1/(1+Math.exp(-logit));}
export function convertGame(schedule:ShlScheduleGame,events:ShlEvent[],model:XgModel):Game{const goals=new Set(events.filter(e=>e.type==='goal'&&e.period>=1&&e.period<=4).map(e=>e.eventUuid||String(e.eventId)));if(goals.size!==schedule.homeTeamInfo.score+schedule.awayTeamInfo.score-(schedule.shootout?1:0))throw Error('Målhändelserna stämmer inte med slutresultatet.');const shots=extractShots(events);if(shots.some(s=>!s.eligible&&!s.emptyNet))throw Error('Målvaktsstatus saknas för delar av matchen.');if(shots.length<20)throw Error('Ofullständigt skottunderlag.');const eligible=shots.filter(s=>s.eligible);if(!eligible.length)throw Error('Målvaktsstatus kunde inte verifieras.');const stat:Stat={gf:0,ga:0,xgf:0,xga:0,cf:0,ca:0,sog:0,soga:0};for(const s of eligible){s.xg=probability(s,model);if(s.home){stat.cf!++;stat.xgf+=s.xg;if(['goal','saved'].includes(s.outcome))stat.sog!++;if(s.outcome==='goal')stat.gf++;}else{stat.ca!++;stat.xga+=s.xg;if(['goal','saved'].includes(s.outcome))stat.soga!++;if(s.outcome==='goal')stat.ga++;}}return {id:`shl-${schedule.uuid}`,date:schedule.startDateTime.slice(0,10),season:SHL_SEASON,home:nameByCode[schedule.homeTeamInfo.code]||schedule.homeTeamInfo.names.full,away:nameByCode[schedule.awayTeamInfo.code]||schedule.awayTeamInfo.names.full,resultHome:schedule.homeTeamInfo.score,resultAway:schedule.awayTeamInfo.score,overtime:schedule.overtime||schedule.shootout,shootout:schedule.shootout,goals:goalEvents(events),source:'SHL:s publika matchhändelser · egna beräkningar',sourceUrl:sourceUrl(schedule.uuid),model:model.name,stats:{all:stat},shots:eligible,coverage:{totalRegulationShots:shots.length,usedShots:eligible.length,emptyNetShots:shots.filter(s=>s.emptyNet).length,unknownKeeperShots:shots.filter(s=>!s.eligible&&!s.emptyNet).length},fetchedAt:new Date().toISOString()};}
