import fs from 'node:fs/promises';
import {convertGame,sourceUrl,SHL_SCHEDULE_URL} from '../lib/shl.ts';
const path=new URL('../data/shl-2026.json',import.meta.url),publicPath=new URL('../public/data/shl-2026.json',import.meta.url);
const snapshot=JSON.parse(await fs.readFile(path,'utf8')),model=JSON.parse(await fs.readFile(new URL('../data/xg-model.json',import.meta.url),'utf8'));
async function get(url){let last;for(let i=0;i<3;i++){try{const r=await fetch(url,{headers:{Accept:'application/json','User-Agent':'Isbild/1.0 public SHL fan analytics'},signal:AbortSignal.timeout(20000)});if(!r.ok)throw Error(`Source HTTP ${r.status}`);return await r.json();}catch(e){last=e;if(i<2)await new Promise(resolve=>setTimeout(resolve,1000*(i+1)));}}throw last;}
const schedule=await get(SHL_SCHEDULE_URL);if(!Array.isArray(schedule.gameInfo)||schedule.gameInfo.length<300)throw Error('Unexpected SHL schedule format. Existing snapshot retained.');
const all=new Map(snapshot.games.map(g=>[g.id,g]));const cutoff=new Date(Date.now()-8*86400000).toISOString().slice(0,10),stale=Date.now()-12*3600000;const completed=schedule.gameInfo.filter(g=>g.state==='post-game');const pending=completed.filter(g=>{const old=all.get('shl-'+g.uuid);return !old||old.model!==model.name||old.sourceAuditVersion!==2||old.goalieDataVersion!==1||old.playerDataVersion!==1||old.defenseData?.version!==1||(g.startDateTime.slice(0,10)>=cutoff&&(!old.fetchedAt||Date.parse(old.fetchedAt)<stale));});const good=[],errors=[];const sourceAudit={eventTypes:{},fields:{},examples:{}};
for(let offset=0;offset<pending.length;offset+=3){const batch=pending.slice(offset,offset+3);const result=await Promise.allSettled(batch.map(async g=>{const events=await get(sourceUrl(g.uuid));if(!Array.isArray(events))throw Error('Invalid event data');for(const e of events){sourceAudit.eventTypes[e.type]=(sourceAudit.eventTypes[e.type]||0)+1;sourceAudit.fields[e.type]=[...new Set([...(sourceAudit.fields[e.type]||[]),...Object.keys(e)])];if(!sourceAudit.examples[e.type]&&['shot','goal','penalty','penaltyEnd','period','game'].includes(e.type))sourceAudit.examples[e.type]=e;}return {...convertGame(g,events,model),sourceAuditVersion:2};}));result.forEach((r,i)=>{if(r.status==='fulfilled')good.push(r.value);else errors.push(`${batch[i].uuid}: ${r.reason}`);});console.log(`Validated ${Math.min(offset+3,pending.length)}/${pending.length} pending games`);}
// All-or-nothing update prevents publication of a partially successful refresh.
if(errors.length)throw Error('Sync failed. Prior snapshot retained. '+errors.join('; '));
if(good.length){good.forEach(g=>all.set(g.id,g));const updated={...snapshot,sourceAudit,updatedAt:new Date().toISOString(),games:[...all.values()].sort((a,b)=>a.date.localeCompare(b.date)||a.id.localeCompare(b.id))};await fs.writeFile(path,JSON.stringify(updated)+'\n');await fs.mkdir(new URL('../public/data/',import.meta.url),{recursive:true});await fs.writeFile(publicPath,JSON.stringify(updated)+'\n');console.log(`Updated ${good.length} games; ${updated.games.length} total.`);}else{await fs.writeFile(publicPath,JSON.stringify(snapshot)+'\n');console.log('No stale or new completed games. Snapshot unchanged.');}
