import fs from 'node:fs/promises';
import {parseHaSnapshot,haName,haMatchEvents} from '../lib/ha.ts';
const root=new URL('../',import.meta.url),host='https://hockeyallsvenskan.se';
async function get(path,body){let last;for(let i=0;i<3;i++){try{const r=await fetch(host+path,{...(body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{}),signal:AbortSignal.timeout(60000)});if(!r.ok)throw Error(`HA HTTP ${r.status}`);return path.includes('/pages/')?await r.text():await r.json();}catch(e){last=e;}}throw last;}
const base={league:'HA',phase:'HA',season:'2026',team_side:'all',team:'all',against_team:'all',all_results:'all'};
const requests={games:['all-time-games-stats',{...base,categories:'all',game_status:'played',page:1,page_size:400}],players:['all-time-skaters-stats',{...base,categories:'summary',position:'all',ages:'all',page:1,page_size:1000}],goalies:['all-time-goalkeepers-stats',{...base,categories:'summary',ages:'all',page:1,page_size:1000}],offensive:['all-time-teams-stats',{...base,categories:'offensive'}],corsi:['all-time-teams-stats',{...base,categories:'corsi_fenwick_pdo'}],pp:['all-time-teams-stats',{...base,categories:'power_play'}],pk:['all-time-teams-stats',{...base,categories:'penalty_kill'}]};
const pairs=await Promise.all(Object.entries(requests).map(async([key,[path,body]])=>[key,await get('/api/'+path,body)]));const snapshot=parseHaSnapshot(Object.fromEntries(pairs),new Date().toISOString());
const html=await get('/pages/matcher');let calendar;
for(const m of html.matchAll(/self\.__next_f\.push\((\[.*?\])\)<\/script>/g)){const chunk=JSON.parse(m[1])[1];if(typeof chunk!=='string')continue;for(const line of chunk.split('\n'))if(line.includes('"games.game-calendar-')){const p=JSON.parse(line.slice(line.indexOf(':')+1));calendar=p[3].games;}}
if(!Array.isArray(calendar)||calendar.length<300)throw Error('HA calendar format changed; previous snapshot retained');
let previous;try{previous=JSON.parse(await fs.readFile(new URL('data/ha-2026.json',root),'utf8'));}catch{}
const old=new Map((previous?.games||[]).map(g=>[g.id,g]));const cutoff=new Date(Date.now()-8*86400000).toISOString().slice(0,10),stale=Date.now()-12*3600000;
for(let start=0;start<snapshot.games.length;start+=4){await Promise.all(snapshot.games.slice(start,start+4).map(async g=>{const saved=old.get(g.id);if(saved?.fetchedAt&&(g.date<cutoff||Date.parse(saved.fetchedAt)>stale)){Object.assign(g,{players:saved.players,goalies:saved.goalies,eventCoverage:saved.eventCoverage,fetchedAt:saved.fetchedAt,url:saved.url});return;}const entry=calendar.find(c=>haName(c.homeStatNetId)===g.home&&haName(c.awayStatNetId)===g.away&&c.scheduledDateTime.slice(0,10)===g.date);if(!entry?.isCompleted)throw Error('Completed HA match missing in calendar');const request=Object.fromEntries(['statNetGameNumber','homeStatNetId','awayStatNetId','playedDateTime','scheduledDateTime'].map(k=>[k,entry[k]]));const events=await get('/api/play-by-play',request);Object.assign(g,haMatchEvents(events,entry.homeStatNetId,entry.awayStatNetId),{url:host+'/games/'+entry.slug+'/view',fetchedAt:new Date().toISOString()});}));console.log(`Verified HA events ${Math.min(start+4,snapshot.games.length)}/${snapshot.games.length}`);}
const text=JSON.stringify(snapshot)+'\n';await fs.writeFile(new URL('data/ha-2026.json',root),text);await fs.writeFile(new URL('public/data/ha-2026.json',root),text);console.log(`Hockeyallsvenskan: ${snapshot.games.length} games, ${snapshot.players.length} players, ${snapshot.goalies.length} goalkeepers. No coordinates: xG/GSAx unavailable.`);
